
default: &default
  adapter: postgresql
  encoding: unicode
  username: hnbmunoz  
  password: g3tP4$$W0rd
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dandyleon_development


test:
  <<: *default
  database: dandyleon_test

# production:
#   <<: *default
#   database: dandyleon_production
#   username: dandyleon_core
#   password: <%= ENV["DANDYLEON_CORE_DATABASE_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>